name: offline_online_sync_testing_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.0
  connectivity_plus: ^6.1.1
  flutter:
    sdk: flutter
  path: ^1.9.0
  rxdart: ^0.28.0
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
