// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_UPmK_Tox7TZ6CRk4kc9hUWxe3_Q0q4Q',
    appId: '1:754525118093:web:711feb39ca18c52a2f0cc4',
    messagingSenderId: '754525118093',
    projectId: 'offline-online-app-123',
    authDomain: 'offline-online-app-123.firebaseapp.com',
    storageBucket: 'offline-online-app-123.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMm8f016VYbvmeW62OcV-PuEj8F8dNPgk',
    appId: '1:754525118093:android:8918526927cf787f2f0cc4',
    messagingSenderId: '754525118093',
    projectId: 'offline-online-app-123',
    storageBucket: 'offline-online-app-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVT4krbP7oaa1Frcwx9qg8SSrSjWYy8es',
    appId: '1:754525118093:ios:c0db783c064718992f0cc4',
    messagingSenderId: '754525118093',
    projectId: 'offline-online-app-123',
    storageBucket: 'offline-online-app-123.firebasestorage.app',
    iosBundleId: 'com.example.offlineOnlineSyncTestingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVT4krbP7oaa1Frcwx9qg8SSrSjWYy8es',
    appId: '1:754525118093:ios:c0db783c064718992f0cc4',
    messagingSenderId: '754525118093',
    projectId: 'offline-online-app-123',
    storageBucket: 'offline-online-app-123.firebasestorage.app',
    iosBundleId: 'com.example.offlineOnlineSyncTestingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_UPmK_Tox7TZ6CRk4kc9hUWxe3_Q0q4Q',
    appId: '1:754525118093:web:fad52517a4c941fc2f0cc4',
    messagingSenderId: '754525118093',
    projectId: 'offline-online-app-123',
    authDomain: 'offline-online-app-123.firebaseapp.com',
    storageBucket: 'offline-online-app-123.firebasestorage.app',
  );
}
